spring:
  shardingsphere:
    datasource:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.10.1.237:3306/master
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      names: master,slave0,slave1
      slave0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.10.1.237:3306/slave0
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      slave1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.10.1.237:3306/slave1
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
    masterslave:
      master-data-source-name: master
      name: ms
      slave-data-source-names: slave0,slave1
    props:
      sql:
        show: true
